//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Project/Input/TiltActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TiltActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TiltActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TiltActions"",
    ""maps"": [
        {
            ""name"": ""TIlt"",
            ""id"": ""60e3f505-4498-4922-a5c6-005ab5684fc1"",
            ""actions"": [
                {
                    ""name"": ""TiltGyro"",
                    ""type"": ""Value"",
                    ""id"": ""0a23aedc-55b0-48c5-8620-e2a8952963a7"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9e321357-391f-4c6c-8768-3161c17513c3"",
                    ""path"": ""<Gyroscope>/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TiltGyro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TIlt
        m_TIlt = asset.FindActionMap("TIlt", throwIfNotFound: true);
        m_TIlt_TiltGyro = m_TIlt.FindAction("TiltGyro", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TIlt
    private readonly InputActionMap m_TIlt;
    private List<ITIltActions> m_TIltActionsCallbackInterfaces = new List<ITIltActions>();
    private readonly InputAction m_TIlt_TiltGyro;
    public struct TIltActions
    {
        private @TiltActions m_Wrapper;
        public TIltActions(@TiltActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TiltGyro => m_Wrapper.m_TIlt_TiltGyro;
        public InputActionMap Get() { return m_Wrapper.m_TIlt; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TIltActions set) { return set.Get(); }
        public void AddCallbacks(ITIltActions instance)
        {
            if (instance == null || m_Wrapper.m_TIltActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TIltActionsCallbackInterfaces.Add(instance);
            @TiltGyro.started += instance.OnTiltGyro;
            @TiltGyro.performed += instance.OnTiltGyro;
            @TiltGyro.canceled += instance.OnTiltGyro;
        }

        private void UnregisterCallbacks(ITIltActions instance)
        {
            @TiltGyro.started -= instance.OnTiltGyro;
            @TiltGyro.performed -= instance.OnTiltGyro;
            @TiltGyro.canceled -= instance.OnTiltGyro;
        }

        public void RemoveCallbacks(ITIltActions instance)
        {
            if (m_Wrapper.m_TIltActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITIltActions instance)
        {
            foreach (var item in m_Wrapper.m_TIltActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TIltActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TIltActions @TIlt => new TIltActions(this);
    public interface ITIltActions
    {
        void OnTiltGyro(InputAction.CallbackContext context);
    }
}
